# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ee504f3be443e0a883919662317fddf01ac7f63a9c1d0b893d058717c0eacb9db96ecc6e1a887223473a74814cef9084d7808a82b125049835eec22adf610b7

test:
  secret_key_base: 84291713b928e76de0995c8bd776caa23e12551e1b92128508c3d0b15337b263876fee4c7d1c588c2cdb31cffde09f1275099c34fb95f1d87bdb84323644b2dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
